[build-system]
requires = [
  "setuptools>=40.0",
  "wheel",
]


[tool.black]
line-length = 88
target-version = ["py36", "py37", "py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.cache
  | _build
  | build
  | dist
  | tests/python_projects
)/
'''
